"use client";

import React, { use } from "react";
import { LandingHeader } from "@/components/marketing/LandingHeader";
import { LandingFooter } from "@/components/marketing/LandingFooter";
import { FileText, Download, Check, BookOpen, Layers } from "lucide-react";

export default function ResourcesPage({ params }: { params: Promise<{ locale: string }> }) {
  const resolvedParams = use(params);
  const locale = resolvedParams.locale;
  const isFa = locale === "fa";

  const resources = [
    {
      title: isFa ? "راهنمای فنی: بهینه‌سازی ساختار ربات‌ها برای هوش زبانی" : "Guide: Robots.txt & Sitemap for AI",
      desc: isFa ? "مستند جامع پیکربندی متاداده‌ها و هدایت ربات‌های خزش ChatGPT و Claude." : "Learn the optimal robots directives to welcome AI crawler bots safely.",
      type: "PDF Guide",
      size: "2.4 MB",
    },
    {
      title: isFa ? "گزارش بازار: ظهور گراف‌های دانش و موتورهای پاسخگو" : "Market Report: Knowledge Graphs Rise",
      desc: isFa ? "تحلیل روندهای ارجاع و آمار کلیدی سهم بازار برندها در خروجی‌های RAG." : "Statistical survey of commercial mentions in ChatGPT outputs.",
      type: "Whitepaper",
      size: "4.1 MB",
    },
  ];

  return (
    <div className="min-h-screen flex flex-col bg-[var(--background)] text-[var(--text-primary)]" style={{ direction: isFa ? "rtl" : "ltr" }}>
      <LandingHeader />

      {/* Hero Header */}
      <section className="relative pt-32 pb-12 overflow-hidden border-b border-[var(--border)]">
        <div className="absolute top-0 right-1/4 w-[35vw] h-[35vw] bg-gradient-to-br from-[#f97316]/10 to-transparent rounded-full blur-[100px] pointer-events-none -z-10" />
        <div className="mx-auto max-w-6xl px-4 sm:px-6 relative z-10 text-center space-y-6">
          <span className="inline-flex items-center gap-2 rounded-full border border-[#f97316]/30 bg-[#f97316]/10 px-4 py-1.5 text-xs font-bold text-[#f97316]">
            {isFa ? "مرکز منابع و راهنماهای کاربردی" : "Resources Hub"}
          </span>
          <h1 className="font-display font-black text-3xl sm:text-4xl leading-tight">
            {isFa ? "کتابخانه دانلود راهنماهای فنی و نمونه گزارش پلتفرم" : "Download Enterprise Whitepapers & Sample Reports"}
          </h1>
          <p className="text-[var(--text-secondary)] text-sm sm:text-base max-w-2xl mx-auto font-medium">
            {isFa
              ? "دریافت آخرین مقالات علمی، اسناد توصیه‌های کاربردی سئو هوش مصنوعی و راهکارهای کاهش ریسک توهم کلمات کلیدی."
              : "Access structured PDF assets, AEO cheat-sheets, and comprehensive branding analytics blueprints."}
          </p>
        </div>
      </section>

      {/* Download Section (Moved from Page.tsx) */}
      <section className="py-16 bg-[var(--background)]">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="glass-panel rounded-3xl border border-[var(--glass-border)] bg-[var(--glass-bg)] p-8 md:p-12 grid md:grid-cols-[1fr_400px] gap-12 items-center shadow-2xl">
            {/* Download Content */}
            <div className="space-y-6">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#f97316]/10 border border-[#f97316]/30 text-xs font-bold text-[#f97316]">
                <FileText size={12} />
                <span>{isFa ? "مستند تحلیل جامع نمونه" : "Sample Brand Report"}</span>
              </span>

              <h2 className="font-display font-black text-2xl sm:text-3xl text-[var(--text-primary)]">
                {isFa ? "نمونه گزارش کامل تحلیل را دانلود کنید" : "Download Sample Analytics Report"}
              </h2>

              <p className="text-[var(--text-secondary)] leading-relaxed text-xs sm:text-sm font-semibold">
                {isFa
                  ? "با دریافت این سند نمونه، با فرمت و متدولوژی تحلیل ساختاری و تحلیل سهم صدای برند خود در مدل‌های برجسته زبانی به طور دقیق آشنا شوید."
                  : "Explore a fully localized diagnostic document generated by Optimus AI. Review entity graphs and visibility metrics."}
              </p>

              <div className="space-y-3 font-bold text-xs text-[var(--text-muted)]">
                <div className="flex items-center gap-2">
                  <Check size={16} className="text-[#38bdf8]" />
                  <span>{isFa ? "شامل نگاشت ساختار گراف ارتباطات ۱-هاپ" : "Comprehensive 1-hop relation schema mapping"}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Check size={16} className="text-[#38bdf8]" />
                  <span>{isFa ? "تحلیل کلمات کلیدی، استنادها و پایش توهم" : "Factuality analysis and hallucination prevention guidelines"}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Check size={16} className="text-[#38bdf8]" />
                  <span>{isFa ? "شامل راهکارهای عملی و برنامه‌ی تولید محتوای AEO" : "Actionable sitemap optimization checklist for LLMs"}</span>
                </div>
              </div>

              <div className="pt-4">
                <a
                  href="/optimus-ai-sample-report.pdf"
                  download="optimus-ai-sample-report.pdf"
                  className="inline-flex items-center gap-2 px-6 py-3.5 rounded-xl bg-gradient-to-r from-[#38bdf8] to-[#f97316] text-white font-black text-xs sm:text-sm shadow-lg shadow-[#38bdf8]/15 hover:scale-[1.03] transition-transform cursor-pointer"
                >
                  <Download size={16} />
                  <span>{isFa ? "دانلود نمونه گزارش (PDF)" : "Download Sample PDF Report"}</span>
                </a>
              </div>
            </div>

            {/* Premium CSS-only Report Mockup */}
            <div className="relative w-full h-[360px] rounded-2xl border border-[var(--glass-border)] bg-[var(--glass-bg)] p-6 shadow-2xl flex flex-col justify-between overflow-hidden group">
              <div className="absolute inset-0 bg-gradient-to-br from-[#38bdf8]/5 to-transparent opacity-50 pointer-events-none" />
              <div className="absolute -top-12 -right-12 w-24 h-24 bg-gradient-to-br from-[#f97316]/20 to-transparent rounded-full blur-xl group-hover:scale-150 transition-transform duration-500" />

              <div className="flex items-center justify-between border-b border-[var(--border)] pb-4">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#38bdf8] to-[#f97316] flex items-center justify-center text-white font-bold text-xs">AI</div>
                  <div>
                    <h4 className="text-xs font-black text-[var(--text-primary)]">{isFa ? "گزارش وضعیت هوشمندی برند" : "Brand AI Audit"}</h4>
                    <span className="text-[9px] text-[var(--text-muted)] font-mono">ID: #99A1-D8</span>
                  </div>
                </div>
                <span className="text-[10px] px-2.5 py-1 rounded bg-[#38bdf8]/10 text-[#38bdf8] font-bold">{isFa ? "نمونه رسمی" : "SAMPLE REPORT"}</span>
              </div>

              <div className="space-y-4 py-4 flex-1">
                <div className="grid grid-cols-2 gap-3">
                  <div className="p-3 rounded-lg bg-[var(--muted-surface)]/50 border border-[var(--border)]">
                    <span className="text-[9px] text-[var(--text-muted)] uppercase tracking-widest">{isFa ? "صحت داده‌ها" : "Factuality"}</span>
                    <p className="text-base sm:text-lg font-extrabold text-[#38bdf8] font-display">۹۴.۲٪</p>
                  </div>
                  <div className="p-3 rounded-lg bg-[var(--muted-surface)]/50 border border-[var(--border)]">
                    <span className="text-[9px] text-[var(--text-muted)] uppercase tracking-widest">{isFa ? "سهم استناد" : "Citations"}</span>
                    <p className="text-base sm:text-lg font-extrabold text-[#f97316] font-display">۸۴۰ {isFa ? "مرجع" : "Ref"}</p>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <div className="h-2 w-full bg-[var(--border)] rounded-full overflow-hidden">
                    <div className="h-full bg-gradient-to-r from-[#38bdf8] to-[#f97316]" style={{ width: "85%" }} />
                  </div>
                  <div className="flex items-center justify-between text-[10px] text-[var(--text-muted)] font-bold">
                    <span>{isFa ? "انطباق معنایی وب‌سایت" : "Website Semantic Aligned"}</span>
                    <span>۸۵٪</span>
                  </div>
                </div>
              </div>

              <div className="pt-3 border-t border-[var(--border)] flex items-center justify-between text-[10px] text-[var(--text-muted)] font-semibold">
                <span>{isFa ? "پلتفرم هوش مصنوعی اپتیموس" : "Powered by Optimus AI Hub"}</span>
                <span className="font-mono">Page 1 / 18</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Resource Lists Grid */}
      <section className="py-12 bg-[var(--background-subtle)]/10 border-t border-[var(--border)]">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="max-w-2xl mx-auto text-center space-y-3 mb-12">
            <h2 className="font-display font-black text-2xl sm:text-3xl text-gradient-brand">
              {isFa ? "سایر راهنماها و مقالات سفید علمی" : "Scientific Guides & Whitepapers"}
            </h2>
            <p className="text-xs sm:text-sm text-[var(--text-muted)] font-medium">
              {isFa ? "مستندات متنی غنی برای درک کامل اکوسیستم بهینه‌سازی هوش مصنوعی." : "Continuous education tools to help brand professionals navigate GEO."}
            </p>
          </div>

          <div className="grid sm:grid-cols-2 gap-6">
            {resources.map((r, idx) => (
              <div key={idx} className="glass-panel p-6 rounded-2xl border border-[var(--glass-border)] bg-[var(--glass-bg)] flex flex-col justify-between space-y-4 shadow-md">
                <div className="space-y-2">
                  <span className="text-[9px] px-2.5 py-0.5 rounded bg-[#38bdf8]/10 text-[#38bdf8] font-bold uppercase tracking-wider">{r.type}</span>
                  <h3 className="text-sm sm:text-base font-bold font-display text-[var(--text-primary)]">{r.title}</h3>
                  <p className="text-xs text-[var(--text-muted)] leading-relaxed font-semibold">{r.desc}</p>
                </div>

                <div className="flex items-center justify-between pt-4 border-t border-[var(--border)] text-[10px] text-[var(--text-muted)] font-bold">
                  <span>{isFa ? "حجم فایل: " : "Size: "} {r.size}</span>
                  <button className="flex items-center gap-1 text-[#38bdf8] hover:underline cursor-pointer">
                    <Download size={12} />
                    <span>{isFa ? "دانلود رایگان" : "Download Now"}</span>
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <LandingFooter />
    </div>
  );
}
